# Defines a PersistentVolumeClaim (PVC) for MySQL storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc  # Name of the PersistentVolumeClaim
spec:
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi  # Requests 1GiB of storage

---

# Defines a Kubernetes Service to expose the MySQL database
apiVersion: v1
kind: Service
metadata:
  name: loandb-service  # Name of the service
spec:
  selector:
    app: loandb  # Selects pods with the label 'app: loandb'
  ports:
    - protocol: TCP  # Uses TCP protocol
      port: 3307  # Exposes service on port 3307
      targetPort: 3307  # Forwards traffic to port 3307 of the pod
  type: ClusterIP  # Service is only accessible within the cluster

---

# Defines a Deployment for the MySQL database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loandb-deployment  # Name of the Deployment
spec:
  replicas: 1  # Deploys a single instance of MySQL
  selector:
    matchLabels:
      app: loandb  # Selects pods with the label 'app: loandb'
  template:
    metadata:
      labels:
        app: loandb  # Labels the pod as 'app: loandb'
    spec:
      containers:
        - name: mysql  # Name of the MySQL container
          image: mysql:latest  # Uses the latest MySQL image
          args: ["--port=3307"]  # Instructs MySQL to listen on port 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"  # Sets the MySQL root password
            - name: MYSQL_DATABASE
              value: "loandb"  # Creates a database named 'loandb'
          ports:
            - containerPort: 3307  # Exposes port 3307 inside the container
          volumeMounts:
            - mountPath: "/var/lib/mysql"  # Mounts storage at MySQL data directory
              name: mysql-storage  # References the volume named 'mysql-storage'
      volumes:
        - name: mysql-storage  # Defines the volume
          persistentVolumeClaim:
            claimName: mysql-pvc  # Uses the PVC defined earlier
